services:
  redis:
    container_name: whiteboard-redis
    image: redis
    ports:
      - '6379:6379'

  db:
    container_name: whiteboard-db
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: whiteboard
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d whiteboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: whiteboard-backend
    image: ckapiainen/otp_1_group_4-backend:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      DB_URL: jdbc:postgresql://db:5432/whiteboard
      DB_USER: user
      DB_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis

  frontend:
    container_name: whiteboard-frontend
    image: ckapiainen/otp_1_group_4-frontend:latest
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - app

volumes:
  postgres_data:
